### ISSUE TITLE
Bottom sheet feedback

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#436]
Testing the WordPress-pr-12366-build-60402.apk build on a Pixel running android 9.

Story specific: 
- Got a crash when I tried to add tags - not reproduce-able - curious if logs got sent?
- Capitalize the first character of the title 
- Wondering if we should open the sheet with the keyboard up by default to encourage people to give their story a title. (Originally we had planned on requiring stories to have titles, but since we don't require it for regular blog posts I don't think we should force it for story posts.)

More general:
- On the Publish Date settings screen - update the title from "Publish" to "Publish Date" to match with what's on the prior screen. 
- On the Publish Date setting screen - recommend changing label from "Time and Date" to "Date and Time" because the flow goes in that order (choose date, then choose time) 
- Recommend getting rid of the "X" in the upper right of the sheet when editing tags and setting the publish date - I kept pressing it by accident expecting it to cancel /clear my changes rather than dismiss the whole publish sheet. I think when drilling down into the settings you don't need the additional dismiss functionality since the swipe down to dismiss is still there. It feels more straightforward to just have the back arrow.

**Comment by mbshakti** [comment]
@megsfulton Sorry for the late response here. I'm fine with removing the "X" because of the reason you stated for the prepublishing nudges bottom sheet, but to clarify @jd-alexander if we remove it here, we'd have to remove it across the entire app, right? 

I followed @osullivanchris's bottom sheet design proposal, so defer to him if we want to remove the "X" across the entire app. 

(edited comment to remove a P2 link)
