### ISSUE TITLE
Text editing: Vertically center the title in the text styles button toggle

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#535]
>Some of the font style labels sit lower in the containing rectangle than others. Strong feels like it’s not vertically centered compared to Casual, etc.

**Comment by aforcier** [comment]
The text actually _is_ centered vertically - I believe it's moving around because the font itself is drawn higher or lower in the same line (you can see the same thing happen in the actual text - see for example how much farther above the bottom of the cursor text written in 'Playful' is than, say, 'Casual').

It's a bit more obvious what's happening if I bottom-align the text in the button, like this:

![text-style-button-bottom-aligned](https://user-images.githubusercontent.com/9613966/93418230-e23b7200-f8e4-11ea-9120-77002d61fa0a.gif)

There's probably some line adjustment I could do to force them all to be placed the same on the line but that feels like disproportionate effort - I suggest we leave this for now (but keep the issue open).

I'll mark the issue that way but please follow up if you disagree/have another suggestion.

**Comment by megsfulton** [comment]
Hmm, this one's important to me. I either want to make the effort to fix it or redesign the toggle so it's less of an issue.

**Comment by aforcier** [comment]
> Hmm, this one's important to me. I either want to make the effort to fix it or redesign the toggle so it's less of an issue.

Fair enough - I'll put it back on the board and think on it a bit more. 👍
