### ISSUE TITLE
Editing: reording slides sometimes loses text

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#581]
Reported here with video: pbMoDN-1lv-p2#comment-2764

> I edited an already published post and the only thing I did was rearrange the pages. When I published the changes and checked on the web, some of the pages had lost their text.

I was able to reproduce this on my test site. For the story I tested with the it was the last few slides that lost text. The text is still visible in the editor, but not in the published story. https://cloudup.com/c8hELUnR8mG

**Comment by megsfulton** [comment]
Update: 
When I updated the post with the story in the editor after the text became visible on the slides again, the web view shows the text now: https://meganmesses.wordpress.com/2020/10/23/apple-picking/

**Comment by mzorz** [comment]
I was able to reproduce, following these steps (inspired by the video in this [Gutenberg manual test cases report](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3324#issuecomment-814660455):

~1. create a Story with 2 slides, add text to each of them
2. save
3. open the block for editing in the Story composer again
4. reorder the slides (put the second one in the first place now)
5. save
6. open the block for editing once more
7. observe you get the "Limited Story editing" dialog, and the second slide has no text now~


1. create story with 2 slides, add one text on them
2. save
3. go to post, edit post
4. tap block to edit
5. rearrange story: tap and hold the first slide and move it to the right (beware to NEVER TAP on the slide that now is at the first position! this would otherwise refresh the slide and make the text visible)
6. save (verify at this point the block in Gutenberg, which shows the first slide by default,  which was the last slide before step 5, does **not** have an added view)
7. tap UPDATE
8. verify the server version doesn't have an added view on the first slide (was last slide originally)
